<a href="https://colab.research.google.com/github/ajpj1/Antonio-Jesuz/blob/main/Trabalhando_com_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importando a lista de alunos**

In [9]:
import pandas as pd
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 
         'Nota': [4, 7, 5.5, 9],
         'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

In [10]:
dataframe = pd.DataFrame(alunos)

**Transformando em dataframe ou Tabelas**

In [11]:
print(dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Não
1    Pedro   7.0      Sim
2  Roberto   5.5      Não
3   Carlos   9.0      Sim


**Transformando a lista em Serie pandas**

In [12]:
objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [19]:
import numpy as np1
array1 = np.array([6, 12, 2, 9, 10])
array2 = np.array ([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)])
print(array1)
print (array2)

[ 6 12  2  9 10]
[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


**Transformou serie em pandas em lista**

In [21]:
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     2
3     9
4    10
dtype: int64
